version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/pipeline.log
    maxBytes: 10485760
    backupCount: 5

loggers:
  pipeline:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  scraper:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  processor:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  embeddings:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  storage:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console]

